// <auto-generated />
using System;
using KilimoSchoolSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KilimoSchoolSystem.Migrations
{
    [DbContext(typeof(KilimoSchoolSystemContext))]
    [Migration("20230212002627_SeedDataToDatabase")]
    partial class SeedDataToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KilimoSchoolSystem.Models.Stream", b =>
                {
                    b.Property<int>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreamId"));

                    b.Property<string>("StreamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreamId");

                    b.ToTable("Stream");

                    b.HasData(
                        new
                        {
                            StreamId = 1,
                            StreamName = "Form 1A"
                        },
                        new
                        {
                            StreamId = 2,
                            StreamName = "Form 1B"
                        },
                        new
                        {
                            StreamId = 3,
                            StreamName = "Form 1C"
                        });
                });

            modelBuilder.Entity("KilimoSchoolSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("StreamId")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StreamId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            AdmissionNumber = "k123/2020",
                            DOB = new DateTime(2005, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jake Osin",
                            StreamId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            AdmissionNumber = "k124/2020",
                            DOB = new DateTime(2005, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marie Danov",
                            StreamId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            AdmissionNumber = "k125/2020",
                            DOB = new DateTime(2005, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paul Morris",
                            StreamId = 1
                        },
                        new
                        {
                            StudentId = 4,
                            AdmissionNumber = "k126/2020",
                            DOB = new DateTime(2005, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Blessing Nuvida",
                            StreamId = 3
                        });
                });

            modelBuilder.Entity("KilimoSchoolSystem.Models.Student", b =>
                {
                    b.HasOne("KilimoSchoolSystem.Models.Stream", "Stream")
                        .WithMany("Students")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("KilimoSchoolSystem.Models.Stream", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
